//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlienIsolationAudioExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlienIsolationAudioExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] base_library {
            get {
                object obj = ResourceManager.GetObject("base_library", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bnkextr {
            get {
                object obj = ResourceManager.GetObject("bnkextr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packed_codebooks_aoTuV_603 {
            get {
                object obj = ResourceManager.GetObject("packed_codebooks_aoTuV_603", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] python36 {
            get {
                object obj = ResourceManager.GetObject("python36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] quickbms {
            get {
                object obj = ResourceManager.GetObject("quickbms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] revorb {
            get {
                object obj = ResourceManager.GetObject("revorb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;soundbank_names&quot;: [
        ///		{
        ///			&quot;original_id&quot;: 34504,
        ///			&quot;new_name&quot;: &quot;SFX\\Foley\\Pinewood Moves\\HEAVY_OVERALLS_SLOW-10.ogg&quot;
        ///		},
        ///		{
        ///			&quot;original_id&quot;: 47464,
        ///			&quot;new_name&quot;: &quot;Voices\\A1_M0701_RIP_0170.ogg&quot;
        ///		},
        ///		{
        ///			&quot;original_id&quot;: 54520,
        ///			&quot;new_name&quot;: &quot;Voices\\A1_CV5_S_USE_SII_N_A.ogg&quot;
        ///		},
        ///		{
        ///			&quot;original_id&quot;: 73908,
        ///			&quot;new_name&quot;: &quot;SFX\\Missions\\M04\\SPOT_HullMovmentInVent_Creek_BB_A_01.ogg&quot;
        ///		},
        ///		{
        ///			&quot;original_id&quot;: 134229,
        ///			&quot;new_name&quot;: &quot;Voices\\A1_CV6_S_ATT_C.ogg&quot;
        ///		},
        ///		{        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string soundbank {
            get {
                return ResourceManager.GetString("soundbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wavescan {
            get {
                object obj = ResourceManager.GetObject("wavescan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ww2ogg {
            get {
                object obj = ResourceManager.GetObject("ww2ogg", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
