//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlienIsolationAudioParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlienIsolationAudioParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] base_library {
            get {
                object obj = ResourceManager.GetObject("base_library", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bnkextr {
            get {
                object obj = ResourceManager.GetObject("bnkextr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packed_codebooks_aoTuV_603 {
            get {
                object obj = ResourceManager.GetObject("packed_codebooks_aoTuV_603", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] python36 {
            get {
                object obj = ResourceManager.GetObject("python36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] revorb {
            get {
                object obj = ResourceManager.GetObject("revorb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SoundBanksInfo Platform=&quot;PS3&quot; SchemaVersion=&quot;9&quot;&gt;
        ///	&lt;RootPaths&gt;
        ///		&lt;ProjectRoot&gt;F:\BuildAgent\work\d5f94e14b4ebe855\AUDIO\wwise_project\Alien_optimisations\&lt;/ProjectRoot&gt;
        ///		&lt;SourceFilesRoot&gt;F:\BuildAgent\work\d5f94e14b4ebe855\AUDIO\wwise_project\Alien_optimisations\.cache\PS3\&lt;/SourceFilesRoot&gt;
        ///		&lt;SoundBanksRoot&gt;F:\BuildAgent\work\d5f94e14b4ebe855\AUDIO\wwise_project\Alien_optimisations\autobuild\PS3\sound\&lt;/SoundBanksRoot&gt;
        ///		&lt;ExternalSourcesInputFile&gt;&lt;/ExternalSou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOUNDBANKSINFO {
            get {
                return ResourceManager.GetString("SOUNDBANKSINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ww2ogg {
            get {
                object obj = ResourceManager.GetObject("ww2ogg", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
